# Generated by Django 3.1.7 on 2021-04-04 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('grade', models.IntegerField(max_length=5, verbose_name='grade')),
                ('room_num', models.IntegerField(verbose_name='room_num')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('address', models.CharField(max_length=240, verbose_name='address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone_number')),
            ],
        ),
        migrations.CreateModel(
            name='Transport_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_num', models.IntegerField(verbose_name='log_num')),
                ('route_num', models.IntegerField(verbose_name='route_num')),
                ('date', models.DateField(verbose_name='date')),
                ('time_to_arrive', models.TimeField(verbose_name='time_to_arrive')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(verbose_name='student_id')),
                ('teacher_email', models.EmailField(max_length=254, verbose_name='teacher_email')),
                ('grade', models.CharField(max_length=5, verbose_name='grade')),
                ('age', models.IntegerField(verbose_name='age')),
                ('activity_id', models.IntegerField(verbose_name='activity_id')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reef.advisor')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reef.parent')),
            ],
        ),
    ]
