# Generated by Django 3.1.7 on 2021-04-18 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updaterequest',
            name='activity_base',
        ),
        migrations.RemoveField(
            model_name='updaterequest',
            name='activity_curr',
        ),
        migrations.AddField(
            model_name='updaterequest',
            name='new_activity_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ActivityChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('activity_type', models.IntegerField()),
                ('permanent', models.BooleanField(default=False)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reef.student')),
            ],
        ),
    ]
