# Generated by Django 3.1.7 on 2021-04-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0002_auto_20210418_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitychange',
            old_name='student_id',
            new_name='student',
        ),
    ]
