# Generated by Django 3.1.7 on 2021-04-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0002_auto_20210407_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisor',
            name='advisor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
