# Generated by Django 3.1.7 on 2021-04-18 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0003_auto_20210418_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updaterequest',
            old_name='student_id',
            new_name='student',
        ),
    ]
