# Generated by Django 3.1.7 on 2021-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0003_auto_20210516_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='advisor',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
        migrations.AlterField(
            model_name='parent',
            name='password',
            field=models.CharField(default='password', max_length=255),
        ),
    ]
