# Generated by Django 3.1.7 on 2021-04-08 00:33

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0003_auto_20210407_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('new_activity_id', models.IntegerField()),
                ('activity_curr', django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=5)),
                ('activity_base', django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='activity_id',
        ),
        migrations.AddField(
            model_name='student',
            name='activity_base',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=5),
        ),
        migrations.AddField(
            model_name='student',
            name='activity_curr',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=5),
        ),
    ]
