# Generated by Django 3.1.7 on 2021-04-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0004_auto_20210408_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updaterequest',
            name='new_activity_id',
        ),
    ]
