# Generated by Django 3.1.7 on 2021-04-08 01:25

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0005_remove_updaterequest_new_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='activity_base',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=11),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='activity_curr',
            field=django_mysql.models.ListTextField(models.IntegerField(), blank=True, null=True, size=11),
        ),
    ]
