# Generated by Django 3.1.7 on 2021-04-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0006_auto_20210408_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterequest',
            name='activity_base',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='activity_curr',
            field=models.JSONField(blank=True, default=[], null=True),
        ),
    ]
