# Generated by Django 3.1.7 on 2021-04-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reef', '0007_auto_20210408_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='activity_base',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='activity_curr',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='activity_base',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='activity_curr',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
